name: Release
on:
  push:
    branches:
      - main
      - next
      - alpha
      - beta
      - "*.x"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          # UI 4 and below are built for legacy Node 14 applications
          cache: npm
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # No build process yet for this library.
      # We deploy TypeScript and GraphQL definitions as-is.

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release@19
